Reserve WhoAmI for StepperDriver
harp-tech/protocol pull request #36
Opened 2024-02-08 22:43 UTC by filcarv

2024-02-10 08:43 UTC, artursilva0 commented
All the devices in the harp-tech repo have the authorship and copyright as harp-tech. Shouldn't this one be the same? I'm ok either way, just to clarify for the future!

2024-03-26 15:39 UTC, bruno-f-cruz commented
> All the devices in the harp-tech repo have the authorship and copyright as harp-tech. Shouldn't this one be the same? I'm ok either way, just to clarify for the future!

I don't have a problem with either so long as the license is permissive.

2024-04-12 07:33 UTC, artursilva0 approved these changes

2024-04-17 00:08 UTC, bruno-f-cruz requested changes

2025-01-29 16:48 UTC, bruno-f-cruz commented
@filcarv Can you make the changes so we can merge this? Thanks!

2025-01-29 18:03 UTC, filcarv commented on whoami.yml
> +    copyright: tbd
What are you suggesting to remove, @bruno-f-cruz ?

2025-01-29 18:20 UTC, bruno-f-cruz commented on whoami.yml
> +    copyright: tbd
The copyright. it appears as tbd

2025-01-30 23:13 UTC, bruno-f-cruz approved these changes

2025-01-30 23:15 UTC, merged