Add EnvironmentSensor device
harp-tech/protocol pull request #56
Opened 2024-10-10 00:32 UTC by bruno-f-cruz

This PR reserves the WhoAmI for the [Environment Sensor harp device](https://github.com/AllenNeuralDynamics/harp.device.environment_sensor) currently in production at the AIND

2024-10-10 07:20 UTC, artursilva0 requested changes
I believe the URLs have a typo. Should be: https://github.com/AllenNeuralDynamics/harp.device.environment_sensor

2024-10-10 13:56 UTC, bruno-f-cruz commented
@Poofjunior is changing it on our side to keep it standard.

2024-10-10 20:51 UTC, filcarv approved these changes

2024-10-17 07:23 UTC, artursilva0 approved these changes

2024-10-17 14:17 UTC, merged